// Generated by Xata Codegen 0.18.0. Please do not edit.
import {
  BaseClientOptions,
  buildClient,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "todos",
    columns: [
      { name: "title", type: "string" },
      { name: "createdAt", type: "datetime" },
      { name: "createdBy", type: "email" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Todos = InferredTypes["todos"];
export type TodosRecord = Todos & XataRecord;

export type DatabaseSchema = {
  todos: TodosRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://Doga-Fincan-s-workspace-pbeo4t.xata.sh/db/todo",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
